import enum


class EnvVarConstants(enum.StrEnum):
    TWITCH_API_APP_ID = "TWITCH_API_APP_ID"
    TWITCH_API_APP_SECRET = "TWITCH_API_APP_SECRET"
    SLACK_WHALEBOT_OAUTH_TOKEN = "SLACK_WHALEBOT_OAUTH_TOKEN"
    TWITCH_ALERT_SLACK_CHANNEL_ID = "TWITCH_ALERT_SLACK_CHANNEL_ID"
